version: "2.1"
services:
  academy-api:
    build: .
    environment:
      PORT: "5000"
      SHOW_URLS: "true"
      STUDENTS_URL: "192.168.99.111"
      STUDENTS_PORT: "3001"
      STUDENTS_ENTRY: "students-ms/resources/students"
      COURSES_URL: "192.168.99.111"
      COURSE_PORT: "4000"
      COURSES_URL_ENTRY: "courses-ms/resources/courses"
    ports:
      - "5000:5000"
